global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'airflow-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.airflow-exporter'
      type: 'A'
      port: 8000
